### ISSUE TITLE
[Bug]: FTP failed: 'VirtualPrinterFTPServer' object has no attribute 'vp_name'

### ISSUE THREAD

**Issue by Dendrowen** [maziggy/bambuddy#759]
### Bug Description

Virtual printer does not accept jobs anymore after updating to v0.2.2. Bambu studio hangs a while at 10%, then responds with a connection error offering me to retry or reconnect, both of which fail. I can see the virtual printer in the device tab, I have the all certificates saved in printer.cer, the bbl_ca.crt and the one in virtual_printer/1/

### Expected Behavior

When I hit send in bambu studio, I expect the file to upload to bambuddy.

### Steps to Reproduce

1. Go to bambu studio
2. Slice print file
3. Hit send
4. Select the bambuddy virtual printer
5. Hit send again
6. Get the error

### Printer Model

P1S

### Bambuddy Version

0.2.2

### Printer Firmware Version

01.09.01.00

### Installation Method

Docker

### Operating System

Linux (Ubuntu/Debian)

### Relevant Logs / Support Package

[bambuddy-support-20260319-185848.zip](https://github.com/user-attachments/files/26123521/bambuddy-support-20260319-185848.zip)

### Checklist

- [x] I have searched existing issues to ensure this bug hasn't already been reported
- [x] I am using the latest version of Bambuddy
- [x] My printer is set to LAN Only mode
- [x] My printer has Developer Mode enabled

**Comment by maziggy** [comment]
Please use latest daily release and note https://raw.githubusercontent.com/maziggy/bambuddy/refs/heads/dev/docs/migration-vp-ftp-port.md

**Comment by maziggy** [comment]
Your VP is not eenabled in settings.

      "running": false,

**Comment by Dendrowen** [comment]
The migration documents didn't help, the daily update did. Thank you!
